test_utils.py/warn_or_crash_slow_parser() significant figures
It's not OK to print

juriscraper.lib.exceptions.SlownessException: This scraper took 3.372174024581909s to test, which is more than the allowed speed of 1s. Please speed it up for tests to pass.

Limit to three digits of precision to the right of the decimal point (fixed-point).