fix(bap1, mich, michctapp): correct missing await for `download()`, etc. (#2146)
* fix(bap1, mich): correct missing await for `_download()`

Analysis of the large `AbstractSite` heirarchy for mistaken overrides
revealed misuse of `_download()`, which was masked by the fact that
`_download()` returns `Any` and the type of `html` is unspecified.

In 0a12116 (#1843), `download()` of `AbstactSite` was made `async`.
For reasons unknown, the `bap1` usage of `download()` didn't get
updated (while its neighbors did), and `mich` didn't get updates
for either the `download()` usage or its `_download_backwards()`
override. This is all but certain to have been an accident.

It would not be surprising if this is the cause of an unrecognized
bug breaking backscraping for both `bap1` and `mich`. This is
unexplored, but an investigation into "why wasn't this recognized?"
would be merited.

* fix(michctapp): correct missing await for `_request_url_get()`

Futher scrutiny of `async` methods revealed that a call of the async
`_request_url_get()` was called without `await`.

```
juriscraper/opinions/united_states/state/michctapp.py:89: error: Call to untyped function "_request_url_get" in typed context  [no-untyped-call]
```

Note: Making `get_missing_name_and_docket()` async requires several
collateral changes, making `_extract_case_data_from_item()` and
`_process_html()` async.

This was not surfaced directly mypy, because `_request_url_get()`
does not have annotations and this gives rise to the less specific
error, `no-untyped-call`.

Revising the method signatures for the cluster, `_request_url_get()`,
`_request_url_post()`, and `_request_url_mock()` would be a nice
thing to do, but this requires some due diligence (types need
confirmation); this is best saved for later.