fix(pacer): correct file open in several `_main()` functions
The type checker highlighted several places where `decode()`
(intended for `bytes`) was being used on a `str` (which does not
implement it). The fix is a simple matter of adjusting the
`open()` with explicit parameters `"rb"`.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/cweider/Projects/juriscraper/juriscraper/pacer/mobile_query.py", line 159, in <module>
    _main()
    ~~~~~^^
  File "/Users/cweider/Projects/juriscraper/juriscraper/pacer/mobile_query.py", line 153, in _main
    text = f.read().decode("utf-8")
           ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Parsing HTML file at tests/examples/pacer/mobile_queries/dcd.html
```