fix(michctapp): correct missing await for `_request_url_get()`
Futher scrutiny of `async` methods revealed that a call of the async
`_request_url_get()` was called without `await`.

```
juriscraper/opinions/united_states/state/michctapp.py:89: error: Call to untyped function "_request_url_get" in typed context  [no-untyped-call]
```

Note: Making `get_missing_name_and_docket()` async requires several
collateral changes, making `_extract_case_data_from_item()` and
`_process_html()` async.

This was not surfaced directly mypy, because `_request_url_get()`
does not have annotations and this gives rise to the less specific
error, `no-untyped-call`.

Revising the method signatures for the cluster, `_request_url_get()`,
`_request_url_post()`, and `_request_url_mock()` would be a nice
thing to do, but this requires some due diligence (types need
confirmation); this is best saved for later.