fix(type-annotations): fix incorrect type annotations
A mypy analysis yielded the following errors:

```
juriscraper/pacer/appellate_attachment_page.py:208: error: Missing return statement  [return]
juriscraper/pacer/appellate_attachment_page.py:218: error: Missing return statement  [return]
juriscraper/opinions/united_states/state/sc.py:88: error: Missing return statement  [return]
juriscraper/opinions/united_states/state/nh_p.py:197: error: Missing return statement  [return]
juriscraper/opinions/united_states/state/texapp.py:266: error: Module "lxml.html" is not valid as a type  [valid-type]
juriscraper/opinions/united_states/state/texapp.py:320: error: Module "lxml.html" is not valid as a type  [valid-type]
juriscraper/opinions/united_states/state/texapp.py:340: error: Module "lxml.html" is not valid as a type  [valid-type]
juriscraper/opinions/united_states/state/texapp.py:427: error: Module "lxml.html" is not valid as a type  [valid-type]
juriscraper/WebDriven.py:24: error: Module "selenium.webdriver" is not valid as a type  [valid-type]
```

A review of each implementation and its callers shows that there is
nothing that requires substantive change. The issue is resolved by
updating annotated return type to reflect the actual return type;
there is no change in behavior. In `appellate_attachment_page`,
explicit `return None` is added for readibility.