fix(pacer/docket_report.py): python3 support on command-line
When run from the command-line, as python -m
juriscraper.pacer.docket_report, we read the file and must no longer
call .decode() as of Python3.

Fixes:

  File "/Users/jhawk/src/juriscraper/juriscraper/pacer/docket_report.py", line 1284, in <module>
    text = f.read().decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'