fix(type-annotations): correct parameter types of `_download_backwards()`
Analysis of the large `AbstractSite` heirarchy for mistaken overrides
revealed these errors concerning `_download_backwards()`:

```
juriscraper/opinions/united_states/federal_bankruptcy/bap9.py:165: error: "date" object is not iterable  [misc]
juriscraper/opinions/united_states/state/idaho_civil.py:169: error: Missing type parameters for generic type "tuple"  [type-arg]
juriscraper/opinions/united_states/state/miss.py:184: error: Missing type parameters for generic type "tuple"  [type-arg]
juriscraper/opinions/united_states/state/wyo.py:123: error: List item 0 has incompatible type "tuple[datetime | None, datetime]"; expected "tuple[date, date]"  [list-item]
juriscraper/oral_args/united_states/federal_appellate/cafc.py:81: error: "date" object is not iterable  [misc]

```

In each, `_download_backwards()` the types are incorrect otherwise
unhelpful. This is a situtation worse than there being no types.
The patch revises each to use the "correct" type for its
implementation (after a review of the `back_scrape_iterable`
assignment.

Because of differing types across subclasses `_download_backwards()`,
`@override` is not appropriate, but a future revision, build around
a generic would be called for.