fix(scotus): consistently use `int` for `yy`.
Sometimes it was an `int` other times, a `str` was used. That is
no good. It is probable that scrapes performed during the starting
year of the current term (e.g. Oct, 5 2026 to Dec 31, 2026) trigger
an exception during the construction of backscrape (when executing
`"26" + 1`):

```
TypeError: can only concatenate str (not "int") to str
```