fix(state): address missing await in `sd.Site._process_html()`
Initial evaluation of mypy, yielded this error:
```
juriscraper/opinions/united_states/state/sd.py:99: error: Value of type "Coroutine[Any, Any, None]" must be used  [unused-coroutine]
juriscraper/opinions/united_states/state/sd.py:99: note: Are you missing an await?
```

In 0a121163 (#1843), `_get_next_page()` was made `async`. This done,
the effect of its invocation in `_process_html()` changes in a
meaningful way. Failing to update callers with `await` is a common
async migration accident, and this is what appears to have happened
here.

The fix is straight-forward, to `await` the completion and, in turn,
`async`-ify `_process_html()`.

It would not be surprising if this is the cause of an unrecognized
bug in the `sd` scraper - where `cases` is artificially limited to
the first page data race invited by the absent await.